const { default: makeWASocket, useMultiFileAuthState, DisconnectReason } = require('@whiskeysockets/baileys');
const pino = require('pino');
const express = require('express');
const app = express();

// 👇 আপনার ফোন নম্বর এখানে বসান (+ বাদে)
const phoneNumber = "8801865760508"; 

// ডাটাবেস এবং AI ফাইল কানেক্ট করা
const booksDatabase = require('./books.json'); 
const { getGeminiReply } = require('./ai'); // নতুন ফাইলটি কল করা হলো

async function connectToWhatsApp() {
    const { state, saveCreds } = await useMultiFileAuthState('auth_info_baileys');
        
            const sock = makeWASocket({
                    auth: state,
                            printQRInTerminal: false,
                                    logger: pino({ level: "silent" }),
                                            browser: ["Ubuntu", "Chrome", "20.0.04"],
                                                });

                                                    if (!sock.authState.creds.registered) {
                                                            setTimeout(async () => {
                                                                        try {
                                                                                        const code = await sock.requestPairingCode(phoneNumber);
                                                                                                        console.log(`\nYour Pairing Code: ${code}\n`);
                                                                                                                    } catch (err) {
                                                                                                                                    console.log("Error requesting pairing code: ", err);
                                                                                                                                                }
                                                                                                                                                        }, 3000);
                                                                                                                                                            }

                                                                                                                                                                sock.ev.on('creds.update', saveCreds);

                                                                                                                                                                    sock.ev.on('connection.update', (update) => {
                                                                                                                                                                            const { connection, lastDisconnect } = update;
                                                                                                                                                                                    if (connection === 'close') {
                                                                                                                                                                                                const shouldReconnect = lastDisconnect.error?.output?.statusCode !== DisconnectReason.loggedOut;
                                                                                                                                                                                                            if (shouldReconnect) {
                                                                                                                                                                                                                            connectToWhatsApp();
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                } else if (connection === 'open') {
                                                                                                                                                                                                                                                            console.log('✅ WhatsApp কানেক্টেড!');
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                            sock.ev.on('messages.upsert', async m => {
                                                                                                                                                                                                                                                                                    const msg = m.messages[0];
                                                                                                                                                                                                                                                                                            if (!msg.message || msg.key.fromMe) return;

                                                                                                                                                                                                                                                                                                    const remoteJid = msg.key.remoteJid;
                                                                                                                                                                                                                                                                                                            const incomingText = (msg.message.conversation || msg.message.extendedTextMessage?.text || "").trim();

                                                                                                                                                                                                                                                                                                                    if (!incomingText) return; // খালি মেসেজ হলে কিছু করবে না

                                                                                                                                                                                                                                                                                                                            // ১. প্রথমে চেক করবে বই আছে কি না
                                                                                                                                                                                                                                                                                                                                    const foundBook = booksDatabase.find(book => 
                                                                                                                                                                                                                                                                                                                                                book.name.toLowerCase().includes(incomingText.toLowerCase())
                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                if (foundBook) {
                                                                                                                                                                                                                                                                                                                                                                            // বই পাওয়া গেলে পিডিএফ পাঠাবে
                                                                                                                                                                                                                                                                                                                                                                                        await sock.sendMessage(remoteJid, { text: `📚 পেয়েছি! *${foundBook.name}* বইটি আপলোড হচ্ছে...` });
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                await sock.sendMessage(remoteJid, { 
                                                                                                                                                                                                                                                                                                                                                                                                                                document: { url: foundBook.link }, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                mimetype: 'application/pdf', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                fileName: `${foundBook.name}.pdf`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ২. বই না পাওয়া গেলে AI কথা বলবে
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // টাইপিং ইফেক্ট (যেন মনে হয় মানুষ লিখছে)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await sock.sendPresenceUpdate('composing', remoteJid); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const aiResponse = await getGeminiReply(incomingText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await sock.sendMessage(remoteJid, { text: aiResponse });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.get('/', (req, res) => res.send('Bot is running'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.listen(process.env.PORT || 3000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            connectToWhatsApp();